criterion:
  name: ce

aux_criterion:
  distance_constraint:
    weight: 0

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.001
  grad_clip_value: 0

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "fmnist_meta_cnn_train"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False

quantize:
  weight_bit: 8
  input_bit: 8
  
checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "fmnist/meta_cnn/train"
  model_comment: ""
  resume: 0
  restore_checkpoint : ""
  no_linear: 0

permutation:
  force_perm_legal_epoch: 70
  perm_loss_rho: 0.00001
  perm_loss_rho_gamma: 1.3
  warm_up_epoch: 5
  permutation_interval: 3
  rho_epoch: 15
  max_lambda: 10
  optimizer:
    name: adamw
    lr: 0.002
    weight_decay: 0
    grad_clip_value: 1
  n_epochs: 3000

model:
  name: FullOptMetalens
  conv_cfg:
    type: MetaConv1dETE
    mode: phase_mag
    w_bit: 16
    in_bit: 16
    path_multiplier: 1
    path_depth: 2
    enable_xy_pol: False
    enable_alpha: [False, False]
    enable_beta: False
    delta_z_mode: fixed
    pixel_size_mode: fixed
    lambda_mode: fixed
    rotate_mode: fixed
    gumbel_mode: fixed
    enable_identity: False
    swap_mode: fixed
    weight_train: True
    skip_path: False
    scale_mode: bilinear
    skip_meta: False
    delta_z_data: 4
    lambda_data: 0.85
    pixel_size_data: 0.3
    ref_lambda: 0.532
    ref_pixel_size: 0.3
    alpha_train: [False, False]
    lambda_train: False
    delta_z_train: False
    pixel_size_train: False
    gumbel_T: 5
    beta_train: False
    gumbel_decay_rate: 0.956
    encode_mode: complex
    pixel_size_res: 1
    delta_z_res: 10
    phase_res: 1
    lambda_res: 1
    pac: True
    kernel_size_list: [1]
    length: 32
    metalens_init_file_path: {}
  linear_cfg:
    type: QLinear
    w_bit: 16
    in_bit: 16
    out_bit: 16
  kernel_list: [1]
  mid_channel_list: [1]
  kernel_size_list: [32]
  stride_list: [1]
  padding_list: [0]
  dilation_list: [1]
  groups_list: [1]
  encode_mode: complex


debug:
  verboise: 1

