criterion:
  name: ce

aux_criterion:
  swap_loss:
    weight: 0
  alm_loss:
    weight: 0

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.01
  grad_clip_value: 1

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: connectionist_meta_cnn_train
  n_epochs: 50
  batch_size: 8
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 59
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False
  compile: False
  wandb:
    project: metalens_invdes
    entity: scopex
    name: project_GD
  project_GD: True

quantize:
  weight_bit: 8
  input_bit: 8

in_downsample_rate_scheduler:
  n_epochs: 50
  init_ds_rate: 15
  final_ds_rate: 5
  available_ds_rate: [15, 5]
  mode: "milestone"
  milestone: [40]

out_downsample_rate_scheduler:
  n_epochs: 50
  init_ds_rate: 15
  final_ds_rate: 5
  available_ds_rate: [15, 5]
  mode: "milestone"
  milestone: [40]
  
checkpoint:
  save_best_model_k: 1
  checkpoint_dir: "connectionist/meta_cnn/train"
  model_comment: ""
  resume: 0
  restore_checkpoint : ""

model:
  name: Meta_CNNETE_1D
  input_wg_width: 0.3
  input_wg_interval: 1
  conv_cfg:
    type: MetaConv1dETE
    mode: phase_mag
    w_bit: 16
    in_bit: 16
    path_multiplier: 1
    path_depth: 2
    enable_xy_pol: False
    enable_alpha: [False, False]
    enable_beta: False
    delta_z_mode: fixed
    pixel_size_mode: fixed
    lambda_mode: fixed
    rotate_mode: fixed
    gumbel_mode: fixed
    enable_identity: False
    swap_mode: fixed
    weight_train: True
    skip_path: False
    scale_mode: bilinear
    skip_meta: False
    delta_z_data: 4
    lambda_data: 0.85
    pixel_size_data: 0.3
    ref_lambda: 0.85
    ref_pixel_size: 0.3
    alpha_train: [False, False]
    lambda_train: False
    delta_z_train: False
    pixel_size_train: False
    gumbel_T: 5
    beta_train: False
    gumbel_decay_rate: 0.956
    encode_mode: phase
    pixel_size_res: 1
    delta_z_res: 10
    phase_res: 1
    lambda_res: 1
    pac: True
    kernel_size_list: [1]
    length: 32
    metalens_init_file_path: {}
  linear_cfg:
    type: QLinear
    w_bit: 16
    in_bit: 16
    out_bit: 16
  digital_norm_cfg:
    type: BN1d
    affine: True
  digital_act_cfg:
    type: ReLU
    inplace: True
  optical_norm_cfg: None
  optical_act_cfg: None
  kernel_list: [1]
  mid_channel_list: [1]
  kernel_size_list: [32]
  hidden_list: []
  stride_list: [1]
  padding_list: [0]
  dilation_list: [1]
  groups_list: [1]
  pool_out_size: 5
  feature_extractor_type: regular
  feature_dim: 32
  encode_mode: phase

model_test:
  name: Meta_CNNETE_1D
  input_wg_width: 0.3
  input_wg_interval: 1
  conv_cfg:
    type: MetaConv1dETE
    mode: phase_mag
    w_bit: 16
    in_bit: 16
    path_multiplier: 1
    path_depth: 2
    enable_xy_pol: False
    enable_alpha: [False, False]
    enable_beta: False
    delta_z_mode: fixed
    pixel_size_mode: fixed
    lambda_mode: fixed
    rotate_mode: fixed
    gumbel_mode: fixed
    enable_identity: False
    swap_mode: fixed
    weight_train: True
    skip_path: False
    scale_mode: bilinear
    skip_meta: False
    delta_z_data: 4
    lambda_data: 0.85
    pixel_size_data: 0.3
    ref_lambda: 0.85
    ref_pixel_size: 0.3
    alpha_train: [False, False]
    lambda_train: False
    delta_z_train: False
    pixel_size_train: False
    gumbel_T: 5
    beta_train: False
    gumbel_decay_rate: 0.956
    encode_mode: phase
    pixel_size_res: 1
    delta_z_res: 10
    phase_res: 1
    lambda_res: 1
    pac: True
    kernel_size_list: [1]
    length: 32
    metalens_init_file_path: {}
  linear_cfg:
    type: QLinear
    w_bit: 16
    in_bit: 16
    out_bit: 16
  digital_norm_cfg:
    type: BN1d
    affine: True
  digital_act_cfg:
    type: ReLU
    inplace: True
  optical_norm_cfg: None
  optical_act_cfg: None
  kernel_list: [1]
  mid_channel_list: [1]
  kernel_size_list: [32]
  hidden_list: []
  stride_list: [1]
  padding_list: [0]
  dilation_list: [1]
  groups_list: [1]
  pool_out_size: 5
  feature_extractor_type: regular
  feature_dim: 32
  encode_mode: phase

invdes_sharpness_scheduler:
  mode: per_epoch
  init_sharpness: 10
  final_sharpness: 256
  sharpness_peak_epoch: 30
  sharpness_span_per_epoch: 128
  num_train_epochs: 50

debug:
  verboise: 1